apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/web
images:
  - name: ghcr.io/rafex/alpirafex-web
    newName: ghcr.io/rafex/alpirafex-web
    digest: sha256:18ac28897e3d4cbccf9c6617a6ff1ef619645717b2cc064b02cf05d8651d1a6d
